In [1]:
import numpy as np

In [2]:
# 1차원 배열 생성하기
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
# 2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [4]:
# 변수를 사용하여 2차원 배열 생성하기
i_list = [[1, 2, 3], [4, 5, 6]]
b = np.array(i_list)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [5]:
# 배열의 차원 및 크기 확인
print(a.ndim)
print(a.shape)

print(b.ndim)
print(b.shape)

1
(5,)
2
(2, 3)


In [6]:
# 모든 값이 0인 a*b 배열 생성
# dtype = float이 기본이어서 0. << 이렇게 출력됨.

# np.zeros(shpae=(a, b))
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 모든 값이 1인 a*b 배열 생성

# np.ones(shape=(a, b))
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# np.full(shape(a, b), fill_value=c)
a = np.full((2, 3), 5, dtype=np.int8)
print(a)

b = np.full((2, 3), 5, dtype=np.float64)
print(b)

c = np.full((2, 3), 1.5)
print(c)

[[5 5 5]
 [5 5 5]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [9]:
# 대각선 값은 1이고 나머지 값은 0인 a*a 배열 생성

# np.eye(a, b)
a = np.eye(3)
print(a)

b = np.eye(3, 4)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [10]:
# 임의의 값으로 채워진 a*b 배열 생성

# np.random.randn(d0, d1, ... dn)
a = np.random.randn(2, 3)
a

array([[ 2.38578445,  1.58704146,  0.41081842],
       [-2.05785957,  0.39518063,  1.06617952]])

In [11]:
# 슬라이싱

a = np.array([1, 2, 3])
b = a[0:2]
b

array([1, 2])

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a[0:2, 0:2]
b

array([[1, 2],
       [4, 5]])

In [13]:
# numpy 연산

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

c = a - b
print(c)

[5 7 9]
[-3 -3 -3]
